### ISSUE TITLE
appveyor d/l link for Inno Setup

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/FSCW#4]
Tex, does this need to be modified in the appveyor config file with updated releases of this project?:

```
environment:
  INNOSETUP_DOWNLOAD_URL: https://github.com/source-foundry/fscw/releases/download/v0.0.1/innosetup.exe
```

**Comment by texhex** [comment]
No, this 0.0.1 tag is just a placeholder where we keep the latest tested InnoSetup version in our repo. This is simply to avoid that the latest InnoSetup version does not match our script and the build fails. Given that it will be used by font creators without Windows boxes, they have no chance to debug such a case.

But I updated the YML file to explain this:

```
# This URL does not need to be updated.
# We keep the latest tested InnoSetup version in this 0.0.1 "version" to make sure the build works
```

**Comment by chrissimpkins** [comment]
Thanks!  No worries. Just wanted to make sure that docs stated anything that needed to be changed as I went through a test run!
